"""
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""

def even_fibs(n):
    fib_list = []
    a, b = 0, 1
    while a < n:
        if a%2 == 0:
            fib_list.append(a)
        a, b = b, a+b
    return fib_list


print sum(fibs(4000000))





#fib_list = [1, 2]
#
#while fib < 100:
#    fib_list.append(fib_list[-1]+fib_list[-2])
#
#print fib_list
    
